services:
  - type: web
    name: talent-iq-piston
    runtime: docker
    plan: free
    dockerfilePath: piston/Dockerfile

  - type: web
    name: talent-iq-backend
    runtime: node
    plan: free
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm start
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: DB_URL
        sync: false
      - key: CLIENT_URL
        sync: false
      - key: CLERK_SECRET_KEY
        sync: false
      - key: CLERK_PUBLISHABLE_KEY
        sync: false
      - key: STREAM_API_KEY
        sync: false
      - key: STREAM_API_SECRET
        sync: false
      - key: INNGEST_EVENT_KEY
        sync: false
      - key: INNGEST_SIGNING_KEY
        sync: false
      - key: PISTON_API_URL
        value: https://talent-iq-piston.onrender.com
